name: auto_layout_frame
description: Flutter implementation of Figma's Auto Layout frames with support for alignment, padding, gap, resizing, and overflow behavior.
version: 0.1.1

license: MPL-2.0
homepage: https://github.com/kerberjg/auto_layout_frame.dart
repository: https://github.com/kerberjg/auto_layout_frame.dart
issue_tracker: https://github.com/kerberjg/auto_layout_frame.dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.16.0
