name: "package"

on:
  schedule:
  - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/**'
    paths:
      - '**.dart'
      - './*.yaml'
      - .github/workflows/_base*.yaml
      - .github/workflows/package.yaml
  release:
    types: [published]


# call the base workflow with the package path
jobs:
  is-flutter:
    uses: ./.github/workflows/_base-has_flutter.yaml
    with:
      path: '.'

  dart:
    needs: is-flutter
    if: needs.is-flutter.outputs.is_flutter == '0'
    uses: ./.github/workflows/_base-dart.yaml
    with:
      path: '.'

  flutter:
    needs: is-flutter
    if: needs.is-flutter.outputs.is_flutter == '1'
    uses: ./.github/workflows/_base-flutter.yaml
    with:
      path: '.'
