name: "package"

on:
  schedule:
  - cron: "0 12 * * 3"
  pull_request:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths:
      - "**.dart"
      - "./*.yaml"
      - .github/workflows/package.yaml
  release:
    types: [published]

# call the base workflow with the package path
jobs:
  ci:
    uses: kerberjg/dart_flutter_ci_experiments/.github/workflows/pipeline.yaml@4224e695167e35d90952e21953b2f933b0f045b0
    with:
      path: "."
      min-publish-score: 150
